export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PATHS_SUCCESS = 'LOAD_PATHS_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const ADD_PATH_FOR_USER_SUCCESS = 'ADD_PATH_FOR_USER_SUCCESS';
export const REMOVE_PATH_FOR_USER_SUCCESS = 'REMOVE_PATH_FOR_USER_SUCCESS';

export const CREATE_PATH_SUCCESS = 'CREATE_PATH_SUCCESS';
export const UPDATE_PATH_SUCCESS = 'UPDATE_PATH_SUCCESS';
export const CREATE_STEP_SUCCESS = 'CREATE_STEP_SUCCESS';

export const ADD_STEP_TO_PATH_SUCCESS = 'ADD_STEP_TO_PATH_SUCCESS';
export const CONFIRM_PATH_SUCCESS = 'CONFIRM_PATH_SUCCESS';

export const GET_PATH_SUCCESS = 'GET_PATH_SUCCESS';
export const UPDATE_STEP_SUCCESS = 'UPDATE_STEP_SUCCESS';
